experiment_name: l96_training_data_t20000
run_module: run_single_l96

simulation_type: single

# Lorenz '96 parameters
K: 8                
J: 32               
F: [18.0, 20.0]          
h: 1.0              
b: 10.0           
c: 10.0

# Time parameters
total_time: 20000
spin_up_time: 20
dt: 0.001
si: 0.005

# Plotting
plot: true
plot_start_time: 0 # start plotting at 90 time units

# Output
results_dir: results
save_backend: zarr

# Miscellaneous
seed: 0
